### ISSUE TITLE
Login screen impossible to pass on small screens

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/wordcloud-app#11]
Need to redesign the "choose group" dialogue.  Either make it scrollable, or remove dialog and add it as 'alert' <div> at the top of the page on first entry.

**Comment by chrismclarke** [comment]
Tried to use paper-dialog-scrollable but didn't seem to play correctly with the paper-listbox child element. For now the dialog is called directly from my-app component (as doesn't always behave properly from within other components) and so can use full screen size. Suggest reviewing after full group structure implemented (can always minimise padding between items).

**Comment by dave-mills** [comment]
All working well with your full-screen views. Closing
