### ISSUE TITLE
Change by group

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/wordcloud-app#17]
Change the colours to the groups:
- director
- Regional team
- imep
- rms 
- cross cutting
- AC 
- Other

**Comment by chrismclarke** [comment]
groups and colours defined in start-element.html.
colours should be given names the same as those in [material colors](https://material.io/guidelines/style/color.html#)

**Comment by chrismclarke** [comment]
implemented d5c523b272d709c510a9855cbcc8691bd86691bc
