### ISSUE TITLE
Mobile keyboard hides 'add-tag' input

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/wordcloud-app#5]
Steps to replicate: 
- Setup web app on home screen of mobile
- without scrolling, click the "add new tag" input
- keyboard appears and hides input box. 

(tested on Android 6.0 mobile)

**Comment by chrismclarke** [comment]
various sizing changes to fix (e.g. height:70vh, overflow-y:scroll), implemented 0e67155ebccf2e5aebd61c6c75cabe04430ed477
