### ISSUE TITLE
Pretify / streamline tags and tag adding

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/wordcloud-app#6]
Tags look a bit... flat.  It'd be nice to make them look nicer. 

This could also involve pulling the "add new tag" bit into the tag list itself (possibly using something like [paper-tags](https://www.webcomponents.org/element/PolymerEl/paper-tags) )

**Comment by chrismclarke** [comment]
wish I had seen that link before! would have saved some time on figuring out manual implementation/working with iron multiple selects. For now I'm hesitant to replace, but have made some minor changes to .tags class style.

**Comment by dave-mills** [comment]
Implimented via issue #19
